server:
  port: 8001

spring:
  application:
    name: cloud-payment-service
  datasource:
    # 配置数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: ${DB_HOST}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.hcf.entities

eureka:
  client:
    # 表示将自己注册进Eureka Server,默认为true
    register-with-eureka: true
    # 表示是否从Eureka Server抓取已有的注册信息，单节点可以忽略，集群必须设置为true才能配合Ribbon使用负载均衡
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:7001/eureka