server:
  port: 8001

spring:
  application:
    name: cloud-payment-service
  datasource:
    # 数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://localhost:3306/spring_cloud_learning?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: ${DB_PASSWORD}

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.hcf.springcloudlearning.entities