server:
  port: 8001

spring:
  application:
    name: cloud-payment-service
  datasource:
    # 配置数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: ${DB_HOST}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.hcf.entities

eureka:
  client:
    # 表示将自己注册进Eureka Server,默认为true
    register-with-eureka: true
    # 表示是否从Eureka Server抓取已有的注册信息，单节点可以忽略，集群必须设置为true才能配合Ribbon使用负载均衡
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka
  instance:
    instance-id: payment-service-8001
    prefer-ip-address: true
    # 向服务端发送心跳的间隔，默认30s
    lease-renewal-interval-in-seconds: 1
    # 服务段在收到最后一次心跳后的等待间隔上限，默认90s，超时将剔除
    lease-expiration-duration-in-seconds: 2