server:
  port: 9527

spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      discovery:
        locator:
          # 开启从注册中心动态创建路由的功能，利用微服务名进行路由
          enabled: true
      routes:
        #路由id,没有固定规则但要求唯一
        - id: payment_routh
          #匹配后提供服务的路由地址
          uri: http://localhost:8001
          predicates:
            #断言，路径匹配则进行路由,服务对应路由
            - Path=/payment/get/**

        - id: payment_routh2
          uri: lb://cloud-payment-service
          predicates:
            - Path=/payment/lb/**

#        - id: guangzhou2
#          uri: http://pc.nfapp.southcn.com
#          predicates:
#            - Path=/guangzhou

        # 2023-01-04T16:54:18.815948500+08:00[Asia/Shanghai]
        - id: guangzhou3
          uri: http://pc.nfapp.southcn.com
          predicates:
            - Path=/guangzhou
            # After: 在该时间之后路由才会生效
            - After=2023-01-03T16:54:18.815948500+08:00[Asia/Shanghai]
            # Before: 在该时间之前路由才会生效
#            - Before=2023-01-03T16:54:18.815948500+08:00[Asia/Shanghai]
            # Between: 在该时间区间路由才会生效
#            - Between=2023-01-03T16:54:18.815948500+08:00[Asia/Shanghai],2023-01-05T16:54:18.815948500+08:00[Asia/Shanghai]
            # Cookie: 携带Cookie
            - Cookie=username,hcf
            # Header: 携带请求头
            - Header=X-Request-Id,\d+



eureka:
  instance:
    hostname: cloud-gateway-service
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka